### ISSUE TITLE
Getting error while using backbones and head code

### ISSUE THREAD

**Issue by KVSAkhilesh** [Lightning-Universe/lightning-flash#1524]
Getting error while using backbones and head code
if below versions are not compatible please specify the versions we need to use to run the flash, 
please mention what is the compatible torch version to use. 

#### Code sample
from flash.image import ImageClassifier
backbones = ImageClassifier.available_backbones()
print(backbones

### Environment

 - OS (e.g., Linux): Linux
 - Python version: 3.6.9

### Error
![image](https://user-images.githubusercontent.com/44360141/221565812-5c7e5394-b8a7-4962-83df-5dc5fe826bb9.png)

**Comment by Borda** [comment]
seem you have some mismatch with versions, as if you would be using some of the last PL `lightning-utilities`  are dependency of it or if you install latest Flash we have explicitly mentioned it too :rabbit:
