### ISSUE TITLE
ImportError: cannot import name 'Labels' from 'flash.core.classification'

### ISSUE THREAD

**Issue by bayesianist** [Lightning-Universe/lightning-flash#1531]
## 🐛 Bug

`ImportError: cannot import name 'Labels' from 'flash.core.classification' (/usr/local/lib/python3.9/dist-packages/flash/core/classification.py)`

### To Reproduce

```py
from flash.core.classification import Labels
```

**Comment by Borda** [comment]
@bayesianist can you pls share why do you expect that `Labels` shall be there?
