### ISSUE TITLE
Protobuf requirements too strict

### ISSUE THREAD

**Issue by nrudakov** [Lightning-Universe/lightning-flash#1542]
[`protobuf <=3.20.1`](https://github.com/Lightning-Universe/lightning-flash/blob/50139fc33df1c7a5ea2d897d14287fd6f50f8098/requirements.txt#L13) prevents using latest onnx version. Onnx requires [`protobuf >= 3.20.2`](https://github.com/onnx/onnx/blob/b8ffabf76dbf27a796c6b61096b01dcb2e1ec38e/requirements.txt#L2) 
Is it possible to change protobuf requirements to `protobuf < 4`?

**Comment by Borda** [comment]
We would like to check this pining... as we resolved the CI, could you open PR with the suggestion of a higher version...
Note that this pin is just for CI not when you install the package:
https://github.com/Lightning-Universe/lightning-flash/blob/5c42e23fdf2787f9adad2f6f5d0c098d116d8f61/requirements.txt#L1

**Comment by Borda** [comment]
I am afraid we would be able to validate correctness for `0.8.1.post` unless we include almost all patches with `0.8.2` :thinking: what is preventing you from using the latest bug-fix release?

**Comment by DManowitz** [comment]
Actually, I must have misread something, as the protobuf requirements in `requirements/base.txt` for version 0.8.2 are still `protobuf <= 3.20.1`
